apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: timescaledb:5432
    isDefault: true
    database: ${POSTGRES_DB:-gos_rem}
    user: ${POSTGRES_USER:-gos}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-change-me-in-production}
    jsonData:
      sslmode: disable
      timescaledb: true
      postgresVersion: 1600
    editable: false

